### PR TITLE
Minor tweaks to the UI + add knowledge packs

### PR DESCRIPTION
**Pull request by svilupp**
This is great, Pere! Thank you for putting it together.

What started as a simple test ended up more heavy-handed...

Changes
- Added knowledge pack selector
- Minor tweak to input textfield (I don't like having to delete the text each time)
- Change to the new AIHelpMe + outputting RAGResult for future
- Added empty module in src/ folder (I was getting error on Julia 1.10 otherwise)
- Added quick start script in the README
- Added .gitignore
- Added one more model option - Groq-hosted Llama 3 70b, it's a beast!! :D 
- Lastly, the most controversial -- added formatted spec. Any change I make goes through a default formatted if no spec is defined. It would be amazing to have a formatted here by default to ensure consistency (and prevent noisy re-formats / manual un-formatting)

Kudos on the cool hacks (spinner and pull up drawer/mini)

### CODE REVIEW

**Comment by svilupp** [comment]
A few thoughts/suggestions for separate PR:
- Should we organize the different questions in threads? (eg, tab on the left) where the user can easily start a new and switch between them? (as opposed to having all the history but being unable to continue the conversation?)
- Would I mind if I re-organize the code to be mostly inside the AIHelpUI module (except for the App runner)?
It's much easier for me to reason about an app, if it's structured like all other Julia apps (I struggle with nested include calls - one script includes, another script includes inside that, etc)
- For the Stipple App, I'd suggest a separate App module in the src/ folder that will import all the UI and functionality as needed (not to break precompilation. I know Genie apps often fail that, at least for me)
- Could we change the name to AIHelpMeGUI (It's a mouthful, but I think with UI we would have ppl mixing up the GUI. Also, I'd like to keep consistency with the original package name)
- The highlighter doesn't work for me, so I'd be keen to remove it and inside apply `print_html` from RAGTools to enable highlighting what is hallucinated vs not (eg, `PromptingTools.Experimental.RAGTools.print_html(result; add_sources=true, add_scores=true,add_context=true)`) You can see that we can choose that gets printed / we can expose it as mini buttons for the user? In addition, the context details are available in `result.context` (and sources `result.sources`), so we can add them to some expansion card?

**Comment by svilupp** [comment]
Out of curiosity, why use `div+@iif` versus quasar route-tab for the sub-pages? Is it to be more Julian, since we don't have tab-route in stipple? 
Is there a bigger cost in switching (probably not even noticeable, is it)?

**Comment by svilupp** [comment]
Also a few observations - I had a look in the console logs and there is a lot of errors coming through, eg, 
- Around the type checks of the drawer properties
```
vue.js:634 [Vue warn]: Invalid prop: type check failed for prop "width". Expected Number with value 170, got String with value "170".

found in

---> <QDrawer>
       <QLayout>
         <Root>
warn @ vue.js:634
assertProp @ vue.js:1715
validateProp @ vue.js:1641
updateChildComponent @ vue.js:4164
prepatch @ vue.js:3151
patchVnode @ vue.js:6347
updateChildren @ vue.js:6232
patchVnode @ vue.js:6358
patch @ vue.js:6519
Vue._update @ vue.js:3964
updateComponent @ vue.js:4082
get @ vue.js:4494
run @ vue.js:4569
flushSchedulerQueue @ vue.js:4327
(anonymous) @ vue.js:1998
flushCallbacks @ vue.js:1924
Promise.then (async)
timerFunc @ vue.js:1951
nextTick @ vue.js:2008
queueWatcher @ vue.js:4419
update @ vue.js:4559
notify @ vue.js:745
reactiveSetter @ vue.js:1070
proxySetter @ vue.js:4643
mouseout @ VM3500:3
invokeWithErrorHandling @ vue.js:1872
invoker @ vue.js:2197
invokeWithErrorHandling @ vue.js:1872
Vue.$emit @ vue.js:3904
e.<computed> @ quasar.umd.min.js:6
invokeWithErrorHandling @ vue.js:1872
invoker @ vue.js:2197
original._wrapper @ vue.js:7591
vue.js:634 [Vue warn]: Invalid prop: type check failed for prop "breakpoint". Expected Number with value 200, got String with value "200".

found in

---> <QDrawer>
       <QLayout>
         <Root>
       ```
- Some React errors in the beginning:
```plaintext
redirectcheck.a12b5cdc.js:1 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at uG (redirectcheck.a12b5cdc.js:1:126321)
    at u (redirectcheck.a12b5cdc.js:1:67671)
    at ou (redirectcheck.a12b5cdc.js:1:81390)
    at i (redirectcheck.a12b5cdc.js:1:131505)
    at uF (redirectcheck.a12b5cdc.js:1:109355)
    at redirectcheck.a12b5cdc.js:1:109221
    at uI (redirectcheck.a12b5cdc.js:1:109229)
    at uE (redirectcheck.a12b5cdc.js:1:105980)
    at ux (redirectcheck.a12b5cdc.js:1:104535)
    at E (redirectcheck.a12b5cdc.js:1:140522)
    ```
Is it to be expected / ignored? I tried to play with the parameters, but no luck.

**Comment by PGimenez** [comment]
> quasar route-tab

AFAIK we're not using the Vue router so router tabs wouldn't work. Also, remember that we wanted to keep things as simple as we could  so that other people could build their bots based on this one😄

**Comment by PGimenez** [comment]
> This is great, Pere! Thank you for putting it together.
> 
> What started as a simple test ended up more heavy-handed...
> 
> Changes
> 
> * Added knowledge pack selector
> * Minor tweak to input textfield (I don't like having to delete the text each time)
> * Change to the new AIHelpMe + outputting RAGResult for future
> * Added empty module in src/ folder (I was getting error on Julia 1.10 otherwise)
> * Added quick start script in the README
> * Added .gitignore
> * Added one more model option - Groq-hosted Llama 3 70b, it's a beast!! :D
> * Lastly, the most controversial -- added formatted spec. Any change I make goes through a default formatted if no spec is defined. It would be amazing to have a formatted here by default to ensure consistency (and prevent noisy re-formats / manual un-formatting)
> 
> Kudos on the cool hacks (spinner and pull up drawer/mini)

Thanks for the improvements!

What error were you getting without the module? I'm running the app with `using GenieFramework; Genie.loadapp(); up()` and it works fine

The formatting is cool, I used to have one but I've disabled the Julia LSP. What are you using? Perhaps we could add as a CI step.

**Comment by PGimenez** [comment]
> A few thoughts/suggestions for separate PR:
> 
> * Should we organize the different questions in threads? (eg, tab on the left) where the user can easily start a new and switch between them? (as opposed to having all the history but being unable to continue the conversation?)

Similar to the ChatGPT UI? Sure, it'd just be a matter of organizing the history by threads with subdicts in JSON format

> * Would I mind if I re-organize the code to be mostly inside the AIHelpUI module (except for the App runner)?

Not sure what you mean. You mean like having the utility functions in that module? Either way, rather than having a `src` folder we should have a `lib`folder and place any modules in there like we do in [this app](https://github.com/BuiltWithGenie/SeriesForecast). This folder will be automatically loaded by Genie. 

Eventually we'll probably need to split the app's logic into multiple modules, we could follow this structure:

https://learn.genieframework.com/docs/guides/adding-reactive-pages#multiple-app-modules

>   It's much easier for me to reason about an app, if it's structured like all other Julia apps (I struggle with nested include calls - one script includes, another script includes inside that, etc)

Would the `lib` auto import solve this?

> * For the Stipple App, I'd suggest a separate App module in the src/ folder that will import all the UI and functionality as needed (not to break precompilation. I know Genie apps often fail that, at least for me)

In general for Genie/Stipple apps we don't use the Julia package structure. We try to keep files in a flat hierarchy to keep things as simple as possible, and add folders like `lib`, `config`etc. only when needed. People tend to get confused otherwise. Now, if we want to distribute this as a package to leverage precompilation we'll need to think about it. This is something we haven't really solved yet

> * Could we change the name to AIHelpMeGUI (It's a mouthful, but I think with UI we would have ppl mixing up the GUI. Also, I'd like to keep consistency with the original package name)

Sure I'll change it

> * The highlighter doesn't work for me, so I'd be keen to remove it and inside apply `print_html` from RAGTools to enable highlighting what is hallucinated vs not (eg, `PromptingTools.Experimental.RAGTools.print_html(result; add_sources=true, add_scores=true,add_context=true)`) You can see that we can choose that gets printed / we can expose it as mini buttons for the user? In addition, the context details are available in `result.context` (and sources `result.sources`), so we can add them to some expansion card?

That would be cool, and it should play well with Markdown formatting sine it's just HTML

**Pull request merged**
